// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ferpeuvcoigvnddorveu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlcnBldXZjb2lndm5kZG9ydmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDMxNTksImV4cCI6MjA3MzExOTE1OX0.cftnCJkjGCnFUdcg-XiGm_eIOv_uMEq-CkCEZ1gw6dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});